main: com.lordralex.permissionsar.PermissionsAR
name: PermissionsAR
version: 0.0.1
author: Lord_Ralex
permissions:
  par.*:
    default: op
    children:
      par.command.*: true
  par.command.*:
    default: op
    children:
      par.command.help: true
      par.command.debug: true
      par.command.reload: true
  par.command.help:
    default: op
  par.command.debug:
    default: op
  par.command.reload:
    default: op
  par.command:
    default: op
commands:
  par:
    permission: par.command