main: com.lordralex.totalpermissions.TotalPermissions
name: TotalPermissions
version: 0.0.1
author: Lord_Ralex
permissions:
  totalpermissions.*:
    default: op
    children:
      totalpermissions.command.*: true
  totalpermissions.command.*:
    default: false
    children:
      totalpermissions.command: true
      totalpermissions.command.help: true
      totalpermissions.command.debug: true
      totalpermissions.command.reload: true
      totalpermissions.command.backup: true
  totalpermissions.command.help:
    default: false
  totalpermissions.command.debug:
    default: false
  totalpermissions.command.reload:
    default: false
  totalpermissions.command:
    default: false
commands:
  totalpermissions:
    permission: totalpermissions.command
    aliases: ["totalperms", "totalperm", "tperm", "tperms"]